In [1]:
import spacy
!python -m spacy download en_core_web_lg
# import gensim.downloader as api
# wv = api.load('word2vec-google-news-300')

2024-01-20 17:06:49.897383: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-20 17:06:49.897451: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-20 17:06:49.898918: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-01-20 17:06:51.429414: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 587.7/587.7 MB 2.6 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')


In [3]:
nlp = spacy.load("en_core_web_lg")
doc = nlp("dog cat banana")
for token in doc:
  print(token.text, "vector:",token.has_vector)

dog vector: True
cat vector: True
banana vector: True


In [11]:
doc = nlp("dog cat banana fghfgh")
for token in doc:
  print(token.text, "vector:",token.has_vector)

dog vector: True
cat vector: True
banana vector: True
fghfgh vector: False


In [12]:
doc[0].vector.shape

(300,)

In [13]:
doc[1].vector


array([ 3.7032e+00,  4.1982e+00, -5.0002e+00, -1.1322e+01,  3.1702e-02,
       -1.0255e+00, -3.0870e+00, -3.7327e+00,  5.3875e-01,  3.5679e+00,
        6.9276e+00,  1.5793e+00,  5.1188e-01,  3.1868e+00,  6.1534e+00,
       -4.8941e+00, -2.9959e-01, -3.6276e+00,  2.3825e+00, -1.4402e+00,
       -4.7577e+00,  4.3607e+00, -4.9814e+00, -3.6672e+00, -1.8052e+00,
       -2.1888e+00, -4.2875e+00,  5.5712e+00, -5.2875e+00, -1.8346e+00,
       -2.2015e+00, -7.7091e-01, -4.8260e+00,  1.2464e+00, -1.7945e+00,
       -8.1280e+00,  1.9994e+00,  1.1413e+00,  3.8032e+00, -2.8783e+00,
       -4.2136e-01, -4.4177e+00,  7.7456e+00,  4.9535e+00,  1.7402e+00,
        1.8275e-01,  2.4218e+00, -3.1496e+00, -3.8057e-02, -2.9818e+00,
        8.3396e-01,  1.1531e+01,  3.5684e+00,  2.5970e+00, -2.8438e+00,
        3.2755e+00,  4.5674e+00,  3.2219e+00,  3.4206e+00,  1.1200e-01,
        1.0303e-01, -5.8396e+00,  4.6370e-01,  2.7750e+00, -5.3713e+00,
       -5.0247e+00, -2.0212e+00,  5.8772e-01,  1.1569e+00,  1.32

In [14]:
doc[1].vector.shape

(300,)

In [15]:
doc[3].vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [16]:
base_token = nlp("sandwich")
base_token.vector.shape

(300,)

#Similarity

In [19]:
doc = nlp("bread sandwich burger car tiger human rice food sdfsdf")
for token in doc:
  print(f"{token.text} <-> {base_token.text}: ",token.similarity(base_token))

bread <-> sandwich:  0.6341067177397708
sandwich <-> sandwich:  0.9999999823146835
burger <-> sandwich:  0.7900927756758959
car <-> sandwich:  0.1825516115154349
tiger <-> sandwich:  0.11234834480413391
human <-> sandwich:  -0.042971604865238676
rice <-> sandwich:  0.48384042420843604
food <-> sandwich:  0.4348063691643022
sdfsdf <-> sandwich:  0.0


<ipython-input-19-1152dae26a6a>:3: UserWarning: [W008] Evaluating Token.similarity based on empty vectors.
  print(f"{token.text} <-> {base_token.text}: ",token.similarity(base_token))


In [20]:
def similar_words(base_word,word_to_compare):
  base_token  = nlp(base_word)
  doc = nlp(word_to_compare)
  for token in doc:
    print(f"{token.text}  <->  {base_token.text} :",token.similarity(base_token))

In [21]:
similar_words("sandwich","bread sandwich burger car tiger human rice food sdfsdf")

bread  <->  sandwich : 0.6341067177397708
sandwich  <->  sandwich : 0.9999999823146835
burger  <->  sandwich : 0.7900927756758959
car  <->  sandwich : 0.1825516115154349
tiger  <->  sandwich : 0.11234834480413391
human  <->  sandwich : -0.042971604865238676
rice  <->  sandwich : 0.48384042420843604
food  <->  sandwich : 0.4348063691643022
sdfsdf  <->  sandwich : 0.0


<ipython-input-20-160669158a2d>:5: UserWarning: [W008] Evaluating Token.similarity based on empty vectors.
  print(f"{token.text}  <->  {base_token.text} :",token.similarity(base_token))


In [24]:
king = nlp.vocab["king"].vector
man= nlp.vocab["man"].vector
woman =nlp.vocab["woman"].vector
queen = nlp.vocab["queen"].vector
result = king-man+woman

In [26]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity([result],[queen])

array([[0.61780137]], dtype=float32)

# NLP_ Classification using word_enbedding

#End - End project: fake and real news dara

In [27]:
import pandas as pd

In [28]:
import os
os.chdir("/content/drive/MyDrive/NLP")

In [38]:
test = pd.read_csv("Fake_Real_news_test.csv",sep=";")
train = pd.read_csv("Fake_Real_news_train.csv",sep=";")

In [51]:
train.columns


Index(['text', 'label'], dtype='object')

In [42]:
train.shape

(5072, 2)

In [46]:
train['label'].value_counts()

0    2536
1    2536
Name: label, dtype: int64

In [52]:
#convert text to vector
train['Vector'] = train['text'].apply(lambda text:nlp(text).vector)

In [67]:
test['Vector'] = test['text'].apply(lambda text:nlp(text).vector)

In [53]:
train

text  label  \
0     complete sentence exploration orin langelle vo...      0   
1     ten thousand people get fooled fake ballot wit...      0   
2     comment sweep election first thing trump invit...      0   
3     astonish chart show moderate republican endang...      1   
4     clinton ekes win iowa sander kill obama admini...      1   
...                                                 ...    ...   
5067  cannabis protect brain traumatic injury concus...      0   
5068  ooh fuck wednesday november lucas wilde ooh fu...      0   
5069  hillary clinton accuse steal furniture state d...      0   
5070  george w bush ethic lawyer file complaint fbi ...      0   
5071  japan approve already dead tpp deal coalition ...      0   

                                                 Vector  
0     [-1.1114564, 0.66683775, -1.9075222, 0.5938887...  
1     [-0.097442046, 0.69163007, -1.9824628, 0.44911...  
2     [-0.81322074, 0.80318654, -1.7297859, 0.580019...  
3     [-0.90894705, 0.70730793, -1.6369646, 0.535107...  
4     [-2.2340055, -0.25913474, 0.17200941, 1.462138...  
...                                                 ...  
5067  [0.8148753, 1.3958695, -1.493863, -0.27440828,...  
5068  [0.33220023, 0.53760844, -1.600167, -0.1503578...  
5069  [-1.0399305, -0.19901171, -1.7097288, 0.327971...  
5070  [-1.026447, 0.49585733, -1.8817283, 0.60801226...  
5071  [-0.6872281, 0.31391665, -1.4472826, 0.7189907...  

[5072 rows x 3 columns]

In [68]:
y_train = train['label']
x_train = train['Vector'].values
y_test = test['label']
x_test = test['Vector'].values


In [69]:
# from sklearn.model_selection import train_test_split
# x_train,x_test,y_train,y_test = train_test_split(train.Vector.value,train.label,test_size=0.2,random_state=42)

In [70]:
import numpy as np
x_train_stack = np.stack(x_train)
x_test_stack = np.stack(x_test)

In [74]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()


x_train_stack_sc = scaler.fit_transform(x_train_stack)
x_test_stack_sc = scaler.fit_transform(x_test_stack)

model.fit(x_train_stack_sc,y_train)
y_pred = model.predict(x_test_stack_sc)


In [77]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7150793650793651

In [79]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.70      0.75      0.72       625
           1       0.73      0.69      0.71       635

    accuracy                           0.72      1260
   macro avg       0.72      0.72      0.71      1260
weighted avg       0.72      0.72      0.71      1260

