# RNN concepts
# End - End Project


In [1]:
import numpy as np

In [2]:
docs = ['recurrent neural network',
		'neural network',
		'artificial neural',
		'connections between nodes',
		'can create a cycle',
		'allowing output',
		'some nodes to affect subsequent',
		'exhibit temporal',
		'dynamic behavior',
		'type of Neural Network',
    'affect subsequent']

In [3]:
import tensorflow as tf
from keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(oov_token = '<nothing>')


In [4]:
tokenizer.fit_on_texts(docs)

In [5]:
tokenizer.document_count

11

In [6]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[7, 2, 3],
 [2, 3],
 [8, 2],
 [9, 10, 4],
 [11, 12, 13, 14],
 [15, 16],
 [17, 4, 18, 5, 6],
 [19, 20],
 [21, 22],
 [23, 24, 2, 3],
 [5, 6]]

In [7]:
tokenizer.word_index

{'<nothing>': 1,
 'neural': 2,
 'network': 3,
 'nodes': 4,
 'affect': 5,
 'subsequent': 6,
 'recurrent': 7,
 'artificial': 8,
 'connections': 9,
 'between': 10,
 'can': 11,
 'create': 12,
 'a': 13,
 'cycle': 14,
 'allowing': 15,
 'output': 16,
 'some': 17,
 'to': 18,
 'exhibit': 19,
 'temporal': 20,
 'dynamic': 21,
 'behavior': 22,
 'type': 23,
 'of': 24}

In [8]:
tokenizer.word_counts

OrderedDict([('recurrent', 1),
             ('neural', 4),
             ('network', 3),
             ('artificial', 1),
             ('connections', 1),
             ('between', 1),
             ('nodes', 2),
             ('can', 1),
             ('create', 1),
             ('a', 1),
             ('cycle', 1),
             ('allowing', 1),
             ('output', 1),
             ('some', 1),
             ('to', 1),
             ('affect', 2),
             ('subsequent', 2),
             ('exhibit', 1),
             ('temporal', 1),
             ('dynamic', 1),
             ('behavior', 1),
             ('type', 1),
             ('of', 1)])

#Padding concept

```
# This is formatted as code
```



In [9]:
from keras.utils import pad_sequences
post_sequences = pad_sequences(sequences,maxlen=5,padding='post')
pre_sequences = pad_sequences(sequences,maxlen=5,padding='pre')

In [10]:
post_sequences

array([[ 7,  2,  3,  0,  0],
       [ 2,  3,  0,  0,  0],
       [ 8,  2,  0,  0,  0],
       [ 9, 10,  4,  0,  0],
       [11, 12, 13, 14,  0],
       [15, 16,  0,  0,  0],
       [17,  4, 18,  5,  6],
       [19, 20,  0,  0,  0],
       [21, 22,  0,  0,  0],
       [23, 24,  2,  3,  0],
       [ 5,  6,  0,  0,  0]], dtype=int32)

In [11]:
pre_sequences

array([[ 0,  0,  7,  2,  3],
       [ 0,  0,  0,  2,  3],
       [ 0,  0,  0,  8,  2],
       [ 0,  0,  9, 10,  4],
       [ 0, 11, 12, 13, 14],
       [ 0,  0,  0, 15, 16],
       [17,  4, 18,  5,  6],
       [ 0,  0,  0, 19, 20],
       [ 0,  0,  0, 21, 22],
       [ 0, 23, 24,  2,  3],
       [ 0,  0,  0,  5,  6]], dtype=int32)

# Sentiment Analysis using RNN

In [12]:
from keras.datasets import imdb

In [ ]:
imdb.load_data()

In [14]:
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [22]:
(x_train,y_train),(x_test,y_test) = imdb.load_data()

In [23]:
print(len(x_train[0]))

218


In [24]:
from keras.utils import pad_sequences
maxlen = 500
x_train = pad_sequences(x_train,maxlen=maxlen,padding = 'post')
x_test = pad_sequences(x_test,maxlen=maxlen,padding = 'post')

In [25]:
print(len(x_train[0]))
print(len(x_train[100]))

500
500


In [26]:
model = Sequential()
model.add(SimpleRNN(32,input_shape=(500,1),return_sequences=False))
model.add(Dense(1,activation = 'sigmoid'))

In [27]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 32)                1088      
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 1121 (4.38 KB)
Trainable params: 1121 (4.38 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [31]:
model.compile(metrics=['accuracy'],optimizer = 'adam',loss = 'binary_crossentropy')

In [32]:
model.fit(x_train,y_train,epochs = 10,validation_data = (x_test,y_test))

Epoch 1/10
782/782 [==============================] - 83s 103ms/step - loss: 0.7005 - accuracy: 0.5057 - val_loss: 0.6938 - val_accuracy: 0.5072
Epoch 2/10
782/782 [==============================] - 81s 104ms/step - loss: 0.6940 - accuracy: 0.5088 - val_loss: 0.6936 - val_accuracy: 0.5077
Epoch 3/10
782/782 [==============================] - 82s 105ms/step - loss: 0.6944 - accuracy: 0.5035 - val_loss: 0.6939 - val_accuracy: 0.5017
Epoch 4/10
782/782 [==============================] - 79s 102ms/step - loss: 0.6939 - accuracy: 0.5022 - val_loss: 0.6937 - val_accuracy: 0.5051
Epoch 5/10
782/782 [==============================] - 82s 105ms/step - loss: 0.6937 - accuracy: 0.5055 - val_loss: 0.6986 - val_accuracy: 0.5046
Epoch 6/10
782/782 [==============================] - 82s 104ms/step - loss: 0.6937 - accuracy: 0.5052 - val_loss: 0.6936 - val_accuracy: 0.5043
Epoch 7/10
782/782 [==============================] - 83s 106ms/step - loss: 0.6934 - accuracy: 0.5041 - val_loss: 0.6994 - val_ac

In [36]:
import tensorflow
from keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(oov_token = '<nothing>')

In [37]:
tokenizer.fit_on_texts(docs)
tokenizer.word_index

{'<nothing>': 1,
 'neural': 2,
 'network': 3,
 'nodes': 4,
 'affect': 5,
 'subsequent': 6,
 'recurrent': 7,
 'artificial': 8,
 'connections': 9,
 'between': 10,
 'can': 11,
 'create': 12,
 'a': 13,
 'cycle': 14,
 'allowing': 15,
 'output': 16,
 'some': 17,
 'to': 18,
 'exhibit': 19,
 'temporal': 20,
 'dynamic': 21,
 'behavior': 22,
 'type': 23,
 'of': 24}

In [38]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[7, 2, 3],
 [2, 3],
 [8, 2],
 [9, 10, 4],
 [11, 12, 13, 14],
 [15, 16],
 [17, 4, 18, 5, 6],
 [19, 20],
 [21, 22],
 [23, 24, 2, 3],
 [5, 6]]

In [39]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences, padding = 'post')
sequences

array([[ 7,  2,  3,  0,  0],
       [ 2,  3,  0,  0,  0],
       [ 8,  2,  0,  0,  0],
       [ 9, 10,  4,  0,  0],
       [11, 12, 13, 14,  0],
       [15, 16,  0,  0,  0],
       [17,  4, 18,  5,  6],
       [19, 20,  0,  0,  0],
       [21, 22,  0,  0,  0],
       [23, 24,  2,  3,  0],
       [ 5,  6,  0,  0,  0]], dtype=int32)

#Model Architechture


In [40]:
from keras import Sequential
from keras.layers import Dense, SimpleRNN, Embedding, Flatten

model = Sequential()
model.add(Embedding(23, output_dim=2, input_length=500))
model.add(SimpleRNN(32, input_shape = (500,1), return_sequences= False))

model.summary()


Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 500, 2)            46        
                                                                 
 simple_rnn_1 (SimpleRNN)    (None, 32)                1120      
                                                                 
Total params: 1166 (4.55 KB)
Trainable params: 1166 (4.55 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


# Embeddding and Rnn on IMDB data set


In [50]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense, SimpleRNN, Embedding, Flatten
from keras.utils import pad_sequences

In [60]:
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words = 10000)
# (X_train, y_train), (X_test, y_test) = imdb.load_data()

In [77]:
#Data Processing
# step 1 - Visualisation of the data
# step 2 - Zero Padding
X_train = pad_sequences(X_train, padding = 'post', maxlen = 50)
X_test = pad_sequences(X_test, padding = 'post', maxlen = 50)

In [78]:
print(len(X_train[0]))
print(len(X_train[10]))

50
50


In [82]:
model = Sequential()
model.add(Embedding(input_dim = 10000,output_dim = 2,input_length = 50))
model.add(SimpleRNN(32,return_sequences = False))
model.add(Dense(1,activation = 'sigmoid'))
model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 50, 2)             20000     
                                                                 
 simple_rnn_5 (SimpleRNN)    (None, 32)                1120      
                                                                 
 dense_4 (Dense)             (None, 1)                 33        
                                                                 
Total params: 21153 (82.63 KB)
Trainable params: 21153 (82.63 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [83]:
model.compile(metrics = ['accuracy'],optimizer='adam',loss='binary_crossentropy')

In [84]:
model.fit(X_train,y_train,epochs =5,validation_data = (X_test,y_test))

Epoch 1/5
782/782 [==============================] - 18s 22ms/step - loss: 0.6932 - accuracy: 0.5050 - val_loss: 0.6934 - val_accuracy: 0.4998
Epoch 2/5
782/782 [==============================] - 15s 19ms/step - loss: 0.6906 - accuracy: 0.5100 - val_loss: 0.6993 - val_accuracy: 0.5062
Epoch 3/5
782/782 [==============================] - 14s 18ms/step - loss: 0.6809 - accuracy: 0.5213 - val_loss: 0.6962 - val_accuracy: 0.5069
Epoch 4/5
782/782 [==============================] - 14s 18ms/step - loss: 0.6683 - accuracy: 0.5278 - val_loss: 0.7055 - val_accuracy: 0.5054
Epoch 5/5
782/782 [==============================] - 14s 18ms/step - loss: 0.6547 - accuracy: 0.5429 - val_loss: 0.7162 - val_accuracy: 0.5002


In [87]:
test_data = X_test[0][0:50].reshape(1,-1)

In [89]:
if model.predict(test_data)<0:
  print('Negative Review')
else:
  print('Positive Review')

1/1 [==============================] - 0s 26ms/step
Positive Review


# Stacked RNN

In [90]:
# model architecture
model = Sequential()
model.add(Embedding(input_dim = 10000, output_dim = 2, input_length = 50))
model.add(SimpleRNN(32, input_shape = (50,1), return_sequences=True))
model.add(SimpleRNN(32, input_shape = (50,1), return_sequences=False))
model.add(Dense(1,activation = 'sigmoid'))

model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_5 (Embedding)     (None, 50, 2)             20000     
                                                                 
 simple_rnn_6 (SimpleRNN)    (None, 50, 32)            1120      
                                                                 
 simple_rnn_7 (SimpleRNN)    (None, 32)                2080      
                                                                 
 dense_5 (Dense)             (None, 1)                 33        
                                                                 
Total params: 23233 (90.75 KB)
Trainable params: 23233 (90.75 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
